spring:
  application:
    name: data-jpa

  datasource:
    url: jdbc:mariadb://localhost:3306/datajpa
    username: root
    password: dosel2
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
