spring:
  application:
    name: jpabook

  datasource:
    url: jdbc:mariadb://localhost:3306/jpashop
    username: root
    password: dosel2
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace